### ISSUE TITLE
v1.1.1 crashes

### ISSUE THREAD

**Issue by lorensr** [zimme/meteor-collection-behaviours#16]
When I upgrade from `v1.1.0` to `v1.1.1`, I get this:

```
=> Started proxy.                             
=> Started MongoDB.                           
=> Exited with code: 1  
```

With no explanatory output. I tried running `meteor debug` with "Pause on uncaught exceptions" on, but got nothing. Not sure how to further diagnose. Nothing stands out here:

https://github.com/zimme/meteor-collection-behaviours/compare/729d1116f0e134b64acb96edb491cb4341dcb16e...HEAD

Only other time I remember having this error I think the problem was using a variable that hadn't been declared.

**Comment by lorensr** [comment]
Oh! Maybe the reference to `Posts`? I don't see it defined anywhere.

**Comment by zimme** [comment]
Are you talking about the Posts in the examples?

**Comment by lorensr** [comment]
Oh! Thought that was weird. Thought I was looking at a code file, but it was the readme.

**Comment by zimme** [comment]
Could you maybe post the code that attaches/configure the behaviours?

**Comment by lorensr** [comment]
```coffeescript
CollectionBehaviours.configure 'timestampable',
  createdAt: no
  createdBy: 'created_by'
  updatedAt: 'updated'
  updatedBy: 'updated_by'
  systemId: '0'

for c in collections
  c.attachBehaviour 'timestampable'


make_soft = (c) ->
  c.attachBehaviour 'softRemovable',
    removed: 'deleted'
    removedAt: 'deleted'
    removedBy: 'deleted_by'
    restoredAt: 'undeleted'
    restoredBy: 'undeleted_by'

for c in soft_collections
  make_soft c
```

**Comment by zimme** [comment]
Thinking it mightbe because removed aand removedAt is both set to deleted

**Comment by lorensr** [comment]
Good catch, thank you :) But fixing that didn't fix the crash. Narrowing down:

```coffeescript
CollectionBehaviours.configure 'timestampable',
  createdAt: 'insertedAt'

Posts.attachBehaviour 'timestampable'
```

crashes, and commenting it out doesn't crash.

**Comment by zimme** [comment]
If was a problem with the configure function, had forgot a `Match.OneOf` when doing the `check`

**Comment by zimme** [comment]
Thank you for helping me tracking this down, I need to try and find the time to write some tests. Preventing this kinds of errors in the future.

**Comment by lorensr** [comment]
Thanks!

**Comment by zimme** [comment]
```coffeescript
CollectionBehaviours.configure
  'timestampable':
    createdAt: no
    createdBy: 'created_by'
    updatedAt: 'updated'
    updatedBy: 'updated_by'
    systemId: '0'
  'softremovable':
    removed: 'deleted'
    removedAt: 'deleted'
    removedBy: 'deleted_by'
    restoredAt: 'undeleted'
    restoredBy: 'undeleted_by'

CollectionBehaviours.attach collections, ['timestampable', 'softremovable']
```
With the latest changes to this package this should work for you too, but only if `collections` is an array of collections.

**Comment by lorensr** [comment]
Got it, thanks!

**Comment by lorensr** [comment]
Testing out `1.1.2`. This works:

```
CollectionBehaviours.configure 'timestampable',
  createdAt: no
```

This crashes:
```
CollectionBehaviours.configure timestampable:
  createdAt: no
```

**Comment by zimme** [comment]
I'll have a look tonorrow

**Comment by zimme** [comment]
Using `1.1.2` and latest version of `zimme:collection-timestampable` I can't reproduce what you've described.
```coffeescript
CollectionBehaviours.configure timestampable:
  createdAt: no
```
The above code doesn't crash for me and just to be explicit it translates into this js code
```js
CollectionBehaviours.configure({
  timestampable: {
    createdAt: false
  }
});
```

**Comment by lorensr** [comment]
I'm sorry, I forgot about a separate bug where Meteor tells me it has updated to a new version of a package when it actually hasn't. It is fixed.
