### ISSUE TITLE
IE10 Endless loop in checkCollections

### ISSUE THREAD

**Issue by pdiniz13** [zimme/meteor-collection-behaviours#19]
When trying to run CollectionBehaviours.attach(collection, name, options) on IE10 or lower the code is crashing on:

```
check collections, Match.OneOf Mongo.Collection, [Mongo.Collection]
```

In trying to resolve the check IE10 or below goes into a endless loop and crashes.

It only crashes on IE and only for the Mongo.users collections. It works fine on all other browsers and for any other collection on IE. For now the only solution that has worked has been to commend out the line adding the Collection behaviour if the browser is IE or else it crashes the entire browser and the page won't load.

**Comment by zimme** [comment]
Doing a re-write of this package in es2015, I'll have a look at fixing this in that re-write, if you need this faster I'll accept a PR for it against this code base.

**Comment by zimme** [comment]
Closing this as my focus will be here instead. https://github.com/meteor-collectionbehaviours.
