### ISSUE TITLE
Cross-behaviours

### ISSUE THREAD

**Issue by nicooprat** [zimme/meteor-collection-behaviours#21]
Would be interesting to be able to create "cross-behaviours" code.

For example, I'm creating a behaviour which will check if the current user is the owner of a document before updating or removing it. It would be interesting that, in the definition on this behaviour, I could see if the "timestampable" behaviour has already been attached. If yes, I could check for the `createdAt` field by default (or the field the developer specified in the options). If not, developer should specify which field to check.

Perhaps it would be enough to add some data to `this.collection` with behaviours already attached and specified options. Just need to be sure that behaviours are attached in the right order I guess.

Hope I'm clear! Just an idea, you may have a better solution :)

**Comment by zimme** [comment]
Yes, but I would like to minimize data added to the collections.

But what we could do is just keep a map of what behaviours are attached to which collections and add an extra api for accessing that map.

``` js
CollectionBehaviours.attachedBehaviours('collectionName'); // Returns array of behaviour names.
```

I've had plans on adding the possibility to detach behaviours too, in the case the behaviour have a detach function implemented.

But what's first on the agenda is re-writing in es2015, because it will be easier for more people to do pull-requests and maybe even take over maintenance if that will ever be needed.

**Comment by nicooprat** [comment]
Agree, I was thinking of something like:

``` js
this.collection.behaviours =  [
  {
    name: timestampable,
    options: {
      createdAt: ...,
      createdBy: ...,
   }, 
  {
    name: softRemovable,
    options: {
      ...
   }, 
]
```

I think that's not much of datas added, and could be easily be done in current version. But +1 for ES6! (-1 for Coffee though ;))

**Comment by zimme** [comment]
@nicooprat, My thinking was that this data isn't added to the collections, but instead are added to the package code here instead.

In the same way I do for the defined behaviours.

https://github.com/zimme/meteor-collection-behaviours/blob/master/lib/behaviours.coffee#L1

So here we would add `attachedBehaviours` with the information you suggested, and the behaviour authors would use `CollectionBehaviours.attachedBehaviours(<collectionName>/collectionObject);` to get the array of attached behaviours for that collection.

Edit:
I wanna avoid adding/changing/removing things on the collection as much as possible to try and keep the collection objects as close to default as possible. My hope with this is to make inter-operability better with other packages and such.

**Comment by zimme** [comment]
Closing this as I'm shifting my focus here. https://github.com/meteor-collectionbehaviours.

There are some good points here, but I believe we need to think about this again in the context of how the new approach will work.
